apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway
  # namespace: istio-system
  namespace: kgateway-system
spec:
  # gatewayClassName: istio
  gatewayClassName: agentgateway
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: agentgateway
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: agentgateway
  namespace: kgateway-system
spec:
  kube:
    agentGateway:
      ca: https://istiod.istio-system.svc:15012
      image:
        registry: ttl.sh/1755188752
        tag: "24h"
