apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  # namespace: istio-system
  namespace: kgateway-system
spec:
  # gatewayClassName: istio
  gatewayClassName: agentgateway
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: agentwaypoint
spec:
  kube:
    agentGateway:
      image:
        registry: ttl.sh/1755188752
        tag: "24h"
