apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rag-v2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag
      version: v2
  template:
    metadata:
      labels:
        app: rag
        version: v2
    spec:
      containers:
      - name: rag
        image: linsun/rag:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_BASE_URL
          value: http://host.docker.internal:11434
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
      serviceAccountName: rag
  strategy:
    canary:
      steps:
      - setWeight: 33
      - pause: {duration: 10s}
      - setWeight: 66
      - pause: {}
      - setWeight: 100
