apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rag-v2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: rag-v2
        image: linsun/rag:v2
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
