apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: ra
        image: linsun/rag:latest  # You'll need to build and push this image to your registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: OLLAMA_BASE_URL
            value: "http://host.docker.internal:11434"
            # value: "http://ollama:80"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: rag
spec:
  selector:
    app: rag
  ports:
  - port: 80
    targetPort: 8000
